#!/usr/bin/env python

Import('env')
Import('env_modules')

env_detour = env_modules.Clone()

# Thirdparty source files
# TODO: clean this up for recastnav+fastlz
thirdparty_sources = []
thirdparty_dir = "#thirdparty/recastnavigation/"
if env['builtin_recast'] and not env["tools"]:
    thirdparty_sources = [
		"Recast/Source/Recast.cpp",
		"Recast/Source/RecastAlloc.cpp",
		"Recast/Source/RecastArea.cpp",
		"Recast/Source/RecastAssert.cpp",
		"Recast/Source/RecastContour.cpp",
		"Recast/Source/RecastFilter.cpp",
		"Recast/Source/RecastLayers.cpp",
		"Recast/Source/RecastMesh.cpp",
		"Recast/Source/RecastMeshDetail.cpp",
		"Recast/Source/RecastRasterization.cpp",
		"Recast/Source/RecastRegion.cpp",
    ]
# Detour source files
thirdparty_sources += [
    	"Detour/Source/DetourAlloc.cpp",
    	"Detour/Source/DetourAssert.cpp",
    	"Detour/Source/DetourCommon.cpp",
    	"Detour/Source/DetourNavMeshBuilder.cpp",
    	"Detour/Source/DetourNavMesh.cpp",
    	"Detour/Source/DetourNavMeshQuery.cpp",
    	"Detour/Source/DetourNode.cpp",
]

# DetourCrowd source files
thirdparty_sources += [
        "DetourCrowd/Source/DetourCrowd.cpp",
        "DetourCrowd/Source/DetourLocalBoundary.cpp",
        "DetourCrowd/Source/DetourObstacleAvoidance.cpp",
        "DetourCrowd/Source/DetourPathCorridor.cpp",
        "DetourCrowd/Source/DetourPathQueue.cpp",
        "DetourCrowd/Source/DetourProximityGrid.cpp",
]

# DetiurTileCache source files
thirdparty_sources += [
        "DetourTileCache/Source/DetourTileCacheBuilder.cpp",
        "DetourTileCache/Source/DetourTileCache.cpp",
]

thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]
thirdparty_sources += ["#thirdparty/fastlz/fastlz.c"]

env_detour.add_source_files(env.modules_sources, thirdparty_sources)
env_detour.Append(CPPPATH=[thirdparty_dir + "/Recast/Include",
    thirdparty_dir + "/Detour/Include",
    thirdparty_dir + "/DetourCrowd/Include",
    thirdparty_dir + "/DetourTileCache/Include",
    "#thirdparty/fastlz"])
# See https://github.com/recastnavigation/recastnavigation/issues/380
# for Wno-error=class-memaccess
env_detour.Append(CPPFLAGS=["-DNDEBUG", "-DTILE_CACHE", "-Wno-error=class-memaccess"])

# Godot source files
env_detour.add_source_files(env.modules_sources, "*.cpp")

Export('env')
