name: C/C++ CI

on:
  push:
    branches: [ 3.2-skirt ]
  pull_request:
    branches: [ 3.2-skirt ]

jobs:
  build:

    runs-on: [ubuntu-16.04]

    steps:
            - name: install-dependencies
              run: sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev \
                   libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
            - uses: actions/checkout@3.2-skirt
            - name: build
              run: scons platform=x11 target=release_debug
            - uses: actions/upload-artifact@v1.0.0
              name: Upload
              with:
                      name: godot.x11.opt.tools.64
                      path: bin

