name: C/C++ CI

on:
  push:
    branches: [ 3.2-skirt ]
  pull_request:
    branches: [ 3.2-skirt ]

jobs:
  build:

    runs-on: [ubuntu-16.04]

    steps:
            - name: install-dependencies
              run: |
                      sudo apt-get update
                      sudo apt-get install software-properties-common
                      sudo dpkg --add-architecture i386
                      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
                      sudo add-apt-repository -y ppa:savoury1/build-tools
                      sudo apt-get update
                      sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl-dev libglu-dev libasound2-dev libasound2:i386 libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm mingw-w64 libpulse0:i386 gcc-multilib-arm-linux-gnueabi gcc-multilib-arm-linux-gnueabihf
            - uses: actions/checkout@master
            - name: build
              run: |
                      scons platform=x11 target=release_debug bits=64 tools=yes -j3
                      scons platform=x11 target=release_debug bits=64 tools=no -j3
                      scons platform=x11 target=release bits=64 tools=no -j3
                      scons platform=x11 target=release bits=32 tools=no -j3
                      scons platform=server target=release bits=64 tools=yes -j3
            - uses: actions/upload-artifact@v1.0.0
              name: Upload
              with:
                      name: godot.x11.opt.tools.64
                      path: bin
            - uses: actions/upload-artifact@v1.0.0
              name: Upload
              with:
                      name: godot.x11.opt.debug.64
                      path: bin
            - uses: actions/upload-artifact@v1.0.0
              name: Upload
              with:
                      name: godot.x11.opt.64
                      path: bin
            - uses: actions/upload-artifact@v1.0.0
              name: Upload
              with:
                      name: godot.x11.opt.32
                      path: bin
            - uses: actions/upload-artifact@v1.0.0
              name: Upload
              with:
                      name: godot_server.x11.opt.tools.64
                      path: bin

